(()=>{'use strict';const A=window.HydroAnalytics,B=window.HYDRO_BASE,$=id=>document.getElementById(id);if(!A||B?.schemaVersion!==3){$('error').hidden=false;$('error').textContent='Base ou módulo analítico indisponível.';return}
const C={2020:'#577d9d',2021:'#ab725e',2022:'#72976a',2023:'#927caf',2024:'#bb913d',2025:'#647f8b',2026:'#b42336'};
const S={view:'previsao',river:'Todos',station:'manaus',years:new Set([2020,2021,2022,2023,2024,2025,2026]),records:JSON.parse(JSON.stringify(B.records)),models:{},chart:null};
const nf=(x,n=2)=>x==null?'—':Number(x).toLocaleString('pt-BR',{minimumFractionDigits:n,maximumFractionDigits:n}),sg=(x,n=2)=>x==null?'—':(x>0?'+':'')+nf(x,n),dd=d=>d?d.slice(8,10)+'/'+d.slice(5,7)+'/'+d.slice(0,4):'—',esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const meta=()=>B.stations.find(s=>s.id===S.station),model=()=>S.models[S.station],height=v=>v==null?null:v-($('reference').value==='nr'?meta().nr:0),unit=()=>$('reference').value==='nr'?'m acima/sob NR':'m na régua';
function updateModels(){S.models=Object.fromEntries(B.stations.map(m=>[m.id,A.calculate(m,S.records[m.id]||[])]))}
function setView(view){S.view=view;document.querySelectorAll('.view').forEach(e=>e.hidden=e.id!==view);document.querySelectorAll('[data-view]').forEach(e=>e.classList.toggle('active',e.dataset.view===view));render()}
function choices(){const rivers=['Todos',...new Set(B.stations.map(s=>s.river))];$('river').innerHTML=rivers.map(r=>`<option>${r}</option>`).join('');$('river').value=S.river;const possible=B.stations.filter(s=>S.river==='Todos'||s.river===S.river);if(!possible.some(s=>s.id===S.station))S.station=possible[0].id;$('station').innerHTML=possible.map(s=>`<option value="${s.id}">${s.name}</option>`).join('');$('station').value=S.station}
function metric(label,value,detail){return `<article class="metric"><span class="label">${label}</span><strong>${value}</strong><small>${detail}</small></article>`}
function renderSummary(){const m=model(),s=meta(),last=m.last,fc7=m.forecast.find(f=>f.date===A.add(m.cut,7)),future=m.forecast.at(-1),valid=last?.valid;
 $('summary').innerHTML=metric('Nível observado',valid?sg(height(last.value))+' m':'—',`${unit()} · ${dd(m.cut)}`)+metric('Variação em 15 dias',sg(m.rates.find(r=>r.days===15)?.delta)+' m','Diferença observada')+metric('Tendência em +7 dias',fc7?sg(height(fc7.value))+' m':'—',`${unit()} · ${fc7?dd(fc7.date):'sem estimativa'}`)+metric('Cenário em 31/12',future?sg(height(future.value))+' m':'—',`${unit()} · ${future?.n||0} análogos`);
 $('header-date').textContent='Base: '+dd(m.cut);$('chart-status').textContent=`${s.name} · ${s.river} · última leitura ${dd(m.cut)} · NR ${nf(s.nr,3)} m`;
}
function renderYears(){const years=new Set(model().series.map(r=>Number(r.date.slice(0,4))));$('year-switches').innerHTML=Array.from({length:7},(_,i)=>i+2020).map(y=>`<button class="year" style="--line:${C[y]};--wash:${C[y]}13" data-year="${y}" aria-pressed="${S.years.has(y)}" ${years.has(y)?'':'disabled'}><i></i>${y}</button>`).join('')}
function renderRates(){const labels={1:'Diária',7:'Semanal',15:'Quinzenal',30:'Mensal',182:'Semestral',365:'Anual'};$('rates').innerHTML=model().rates.map(r=>`<tr><td>${labels[r.days]}</td><td>${sg(r.delta)} m</td><td>${sg(r.cmDay)} cm/dia</td></tr>`).join('')}
function renderDiagnosis(){const m=model(),s=meta(),r15=m.rates.find(r=>r.days===15),z=m.z,dir=r15.delta==null?'Indeterminada':r15.delta<0?'Vazante':r15.delta>0?'Enchente':'Estável';const seasonal=z==null?'Base insuficiente':Math.abs(z)<1?'Dentro de ±1σ':`${z<0?'Abaixo':'Acima'} da média (${sg(z,1)}σ)`;const low=m.forecast.filter(f=>f.lower!=null).reduce((a,f)=>!a||f.value<a.value?f:a,null);
 $('diagnosis-content').innerHTML=`<div class="diagnosis-grid"><div class="finding"><span>Movimento, 15 dias</span><strong>${dir}</strong><small>${sg(r15.cmDay)} cm/dia</small></div><div class="finding"><span>Condição sazonal</span><strong>${seasonal}</strong><small>${m.historicalN} anos comparáveis</small></div><div class="finding"><span>Mínimo observado em 2026</span><strong>${m.min2026?sg(height(m.min2026.value))+' m':'—'}</strong><small>${dd(m.min2026?.date)}</small></div><div class="finding"><span>Mínimo previsto até dezembro</span><strong>${low?sg(height(low.value))+' m':'—'}</strong><small>${dd(low?.date)} · cenário</small></div></div>`;
 if(s.sipam15==null){$('bulletin-text').textContent='O boletim de 08/10/2026 não traz variação de 15 dias para esta estação. O diagnóstico e o cenário até dezembro usam apenas a planilha carregada.'}else{const b=m.bulletin,minimum=m.forecast.reduce((a,f)=>!a||f.value<a.value?f:a,null),difference=b.localCm==null?null:b.localCm-b.deltaCm;const comparison=b.agreement===null?'Não há leitura válida para comparar o sentido da variação.':b.agreement?'As duas séries indicam vazante.':'As séries indicam sentidos opostos; confira datas e origem das leituras.';$('bulletin-text').innerHTML=`<span class="bulletin-lead">Variação em 15 dias: SIPAMHIDRO <strong>${sg(b.deltaCm,0)} cm</strong>; planilha <strong>${sg(b.localCm,0)} cm</strong> até ${dd(m.cut)}${difference==null?'':` (diferença de ${sg(difference,0)} cm)`}. ${comparison}</span><span>Os gráficos mensais do boletim apontam continuidade da vazante no fim do ano. Nosso cenário situa o mínimo em <strong>${dd(minimum?.date)}</strong>, a partir dos análogos da planilha. O boletim emprega outra base e modelagem; esta é uma comparação de tendência, não uma reprodução da previsão oficial.</span>`}
}
function renderReference(){const s=meta(),m=model();$('datum-table').innerHTML=B.stations.map(r=>`<tr><td>${esc(r.name)}</td><td>${esc(r.river)}</td><td>${nf(r.nr,3)} m</td><td>${esc(r.datumOrigin)}</td><td>${r.pdf?`<a href="files/${r.pdf}" target="_blank" rel="noopener">F-43</a>`:'Nivelamento informado'}</td></tr>`).join('');$('conversion').innerHTML=`<p>${esc(s.name)} · ${esc(s.datum)}</p><div class="equation">${nf(m.last?.value,3)} − ${nf(s.nr,3)} = ${nf(m.last?.value-s.nr,3)} m</div><p>Leitura da régua − NR na régua = altura sobre o NR. Última observação: ${dd(m.cut)}.</p>`;calcDepth()}
function calcDepth(){const m=model(),input=$('sounding').value,n=Number(input);$('depth-result').textContent=!input||!Number.isFinite(n)||n<0?'Informe uma sondagem não negativa.':!$('same-nr').checked?'Confirme ponto e NR da carta.':`${nf(n,2)} + (${sg(m.last.value-meta().nr,3)}) = ${nf(n+m.last.value-meta().nr,3)} m no ponto da estação.`}
function renderScience(){const total=Object.values(S.records).reduce((n,r)=>n+r.length,0),m=model();$('base-facts').innerHTML=`<dt>Planilha</dt><dd>${esc(B.workbook.name)}</dd><dt>Leituras</dt><dd>${total.toLocaleString('pt-BR')}</dd><dt>Estações</dt><dd>8</dd><dt>Corte atual</dt><dd>${dd(m.cut)}</dd><dt>NR</dt><dd>8 referências registradas</dd>`;$('validation-facts').textContent=`${m.method.analogs} análogos para ${meta().name}; ${m.method.hindcastErrors} erros históricos de +7 dias; ${m.quality.flagged} datas sinalizadas nesta estação.`}
function render(){if(S.view==='previsao'){choices();renderSummary();renderYears();renderRates();renderDiagnosis();drawChart()}else if(S.view==='referencia')renderReference();else renderScience()}
function drawChart(){const m=model(),s=meta(),svg=$('chart'),host=svg.parentElement,W=Math.max(320,Math.round(host.clientWidth)),H=Math.max(310,Math.round(host.clientHeight)),L=54,R=W-17,T=16,B=H-34;
 const xday=d=>Math.round((Date.UTC(2025,Number(d.slice(5,7))-1,Number(d.slice(8,10)))-Date.UTC(2025,0,1))/86400000),today=xday(m.cut),span=Number($('window').value),xmin=span===365?0:today-span/2,xmax=span===365?364:today+span/2;
 const selected=[...S.years],obs=m.series.filter(r=>r.valid&&selected.includes(Number(r.date.slice(0,4)))&&r.date.slice(5)!=='02-29'),long=S.years.has(2026)?m.forecast.filter(f=>f.kind==='analog'):[],short=S.years.has(2026)&&$('forecast-short').checked?m.forecast.filter(f=>f.kind==='short'):[],fc=[...short,...long];
 const visible=r=>{const d=xday(r.date);return d>=xmin&&d<=xmax},yvals=[...obs,...fc].filter(visible).map(r=>height(r.value));if($('band').checked)yvals.push(...fc.filter(visible).flatMap(r=>[height(r.lower),height(r.upper)]).filter(v=>v!=null));if(!yvals.length){svg.innerHTML='<text x="20" y="40">Sem dados nesta janela.</text>';return}
 let ymin=Math.min(...yvals),ymax=Math.max(...yvals),pad=Math.max(.15,(ymax-ymin)*.1);ymin-=pad;ymax+=pad;if($('reference').value==='nr'&&ymin<.5&&ymax>-.5){ymin=Math.min(ymin,-.08);ymax=Math.max(ymax,.08)}
 const X=d=>L+(xday(d)-xmin)/(xmax-xmin)*(R-L),Y=v=>B-(height(v)-ymin)/(ymax-ymin)*(B-T),fmtCoord=v=>Number(v).toFixed(1),path=(rows,selector=value=>value.value)=>{let out='',prior=null;for(const r of rows){if(!visible(r)||selector(r)==null){prior=null;continue}const t=xday(r.date),gap=prior===null?0:t-prior;out+=(prior===null||gap>3?'M':'L')+fmtCoord(X(r.date))+' '+fmtCoord(Y(selector(r)))+' ';prior=t}return out.trim()};
 let out=`<title>${s.name}: séries anuais e previsão de 2026</title>`;for(let i=0;i<=5;i++){const v=ymin+(ymax-ymin)*i/5,y=B-i*(B-T)/5;out+=`<line class="grid" x1="${L}" x2="${R}" y1="${y}" y2="${y}"/><text x="${L-8}" y="${y+4}" text-anchor="end">${nf(v,1)}</text>`}
 const months=['JAN','FEV','MAR','ABR','MAI','JUN','JUL','AGO','SET','OUT','NOV','DEZ'];for(let i=0;i<=12;i++){const d=Math.round((Date.UTC(2025,i,1)-Date.UTC(2025,0,1))/86400000);if(d>=xmin&&d<=xmax){const x=L+(d-xmin)/(xmax-xmin)*(R-L);out+=`<line class="grid" x1="${x}" x2="${x}" y1="${T}" y2="${B}"/><text x="${x}" y="${H-9}" text-anchor="middle">${months[i%12]}</text>`}}
 if($('reference').value==='nr'&&ymin<=0&&ymax>=0){const y=Y(s.nr);out+=`<line class="zero" x1="${L}" x2="${R}" y1="${y}" y2="${y}"/><text x="${R-4}" y="${y-5}" text-anchor="end">NR</text>`}
 if(today>=xmin&&today<=xmax){const x=L+(today-xmin)/(xmax-xmin)*(R-L);out+=`<line class="now" x1="${x}" x2="${x}" y1="${T}" y2="${B}"/><text x="${x+5}" y="${T+12}">CORTE</text>`}
 if($('band').checked){const band=fc.filter(r=>visible(r)&&r.lower!=null&&r.upper!=null);if(band.length>1){const top=band.map(r=>`${fmtCoord(X(r.date))},${fmtCoord(Y(r.upper))}`).join(' '),bottom=[...band].reverse().map(r=>`${fmtCoord(X(r.date))},${fmtCoord(Y(r.lower))}`).join(' ');out+=`<polygon points="${top} ${bottom}" fill="#d76d79" fill-opacity=".22"/>`}}
 for(let year=2020;year<=2026;year++){if(!S.years.has(year))continue;const rows=m.series.filter(r=>r.valid&&Number(r.date.slice(0,4))===year&&r.date.slice(5)!=='02-29');const d=path(rows);if(d)out+=`<path d="${d}" fill="none" stroke="${C[year]}" stroke-width="${year===2026?2.6:1.65}" stroke-linecap="round" stroke-linejoin="round"/>`}
 if(short.length)out+=`<path class="forecast" d="${path(short)}" fill="none" stroke="${C[2026]}" stroke-width="2.5"/>`;if(long.length)out+=`<path class="forecast" d="${path(long)}" fill="none" stroke="${C[2026]}" stroke-width="2.3"/>`;
 out+=`<line class="axis" x1="${L}" x2="${R}" y1="${B}" y2="${B}"/><rect class="hit" x="${L}" y="${T}" width="${R-L}" height="${B-T}"/>`;svg.setAttribute('viewBox',`0 0 ${W} ${H}`);svg.innerHTML=out;S.chart={W,H,L,R,T,B,xmin,xmax,obs,fc};$('chart-note').textContent=`m ${$('reference').value==='nr'?'sobre o NR':'na régua'} · faixa empírica 95% nominal`;
}
function hover(e){const g=S.chart;if(!g)return;const rect=$('chart').getBoundingClientRect(),px=(e.clientX-rect.left)*g.W/rect.width,day=Math.round(g.xmin+(px-g.L)/(g.R-g.L)*(g.xmax-g.xmin)),target=A.iso(Date.UTC(2025,0,1)+day*86400000).slice(5);const rows=g.obs.filter(r=>r.date.slice(5)===target).map(r=>[r.date.slice(0,4),r.value]);const f=g.fc.find(r=>r.date.slice(5)===target);if(f)rows.push(['2026 previsão',f.value]);if(!rows.length){$('tooltip').hidden=true;return}const tip=$('tooltip');tip.innerHTML=`<strong>${target.slice(3,5)}/${target.slice(0,2)}</strong>`+rows.map(([y,v])=>`<div>${y}: ${sg(height(v),2)} m</div>`).join('');tip.hidden=false;tip.style.left=Math.min(rect.width-190,Math.max(4,e.clientX-rect.left+12))+'px';tip.style.top=Math.max(8,e.clientY-rect.top-8)+'px'}
function openDB(){return new Promise((resolve,reject)=>{const req=indexedDB.open('hidrometria-zp1-v3',1);req.onupgradeneeded=()=>req.result.createObjectStore('changes',{keyPath:'key'});req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)})}
async function loadChanges(){try{const db=await openDB(),entries=await new Promise((resolve,reject)=>{const req=db.transaction('changes').objectStore('changes').getAll();req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)});for(const r of entries){if(!S.records[r.station])continue;const i=S.records[r.station].findIndex(x=>x[0]===r.ts);if(i<0)S.records[r.station].push([r.ts,r.value]);else S.records[r.station][i][1]=r.value}db.close()}catch(e){$('upload-status').textContent='Armazenamento local indisponível. Esta sessão ainda pode importar a planilha.'}}
function cellValue(c,strings){if(!c)return null;const type=c.getAttribute('t'),v=c.getElementsByTagName('v')[0];if(type==='inlineStr')return c.getElementsByTagName('t')[0]?.textContent||null;if(!v)return null;return type==='s'?strings[Number(v.textContent)]:type==='str'||type==='d'?v.textContent:Number(v.textContent)}
async function parseXlsx(file){if(!window.JSZip)throw Error('Leitor de Excel indisponível');if(file.size>25_000_000)throw Error('Planilha acima de 25 MB');const zip=await JSZip.loadAsync(file),read=async n=>{const x=zip.file(n);if(!x)throw Error(`Arquivo Excel sem ${n}`);return new DOMParser().parseFromString(await x.async('text'),'application/xml')};const shared=zip.file('xl/sharedStrings.xml')?await read('xl/sharedStrings.xml'):null,strings=shared?[...shared.getElementsByTagName('si')].map(si=>[...si.getElementsByTagName('t')].map(t=>t.textContent).join('')):[];const sheet=await read('xl/worksheets/sheet1.xml');if(sheet.getElementsByTagName('parsererror').length)throw Error('XML inválido');const rows=[...sheet.getElementsByTagName('row')],names=B.stations.map(s=>s.name),columns=[];const out=[],seen=new Map();for(const row of rows){const cells=Object.fromEntries([...row.getElementsByTagName('c')].map(c=>[c.getAttribute('r').match(/^[A-Z]+/)[0],cellValue(c,strings)]));const col=i=>{let n=i+1,key='';while(n){n--;key=String.fromCharCode(65+n%26)+key;n=Math.floor(n/26)}return key};if(!columns.length){for(let i=0;i<16;i+=2){const name=cells[col(i+1)];if(!names.includes(name))throw Error('Cabeçalho das oito estações não reconhecido');columns.push(B.stations.find(s=>s.name===name).id)}continue}for(let i=0;i<8;i++){const serial=cells[col(i*2)],value=cells[col(i*2+1)];if(serial==null&&value==null)continue;let ts;if(typeof serial==='number')ts=new Date(Date.UTC(1899,11,30)+Math.round(serial*86400000)).toISOString().slice(0,19);else if(typeof serial==='string'&&/^\d{4}-\d\d-\d\d/.test(serial))ts=serial.slice(0,19).padEnd(19,'0');if(!ts||!Number.isFinite(value))throw Error(`Data ou nível inválido na linha ${row.getAttribute('r')}`);const key=columns[i]+'|'+ts;if(seen.has(key)&&seen.get(key)!==value)throw Error(`Leituras conflitantes na linha ${row.getAttribute('r')}`);seen.set(key,value);out.push({station:columns[i],ts,value})}}return out}
async function importFile(file){const status=$('upload-status');status.textContent='Lendo planilha…';try{const incoming=await parseXlsx(file),maps=Object.fromEntries(B.stations.map(s=>[s.id,new Map(S.records[s.id].map(r=>[r[0],r[1]]))]));let added=0,revised=0,repeated=0;const changes=[];for(const r of incoming){const old=maps[r.station].get(r.ts);if(old===undefined){added++;changes.push({...r,key:r.station+'|'+r.ts})}else if(Math.abs(old-r.value)>1e-6){revised++;changes.push({...r,key:r.station+'|'+r.ts})}else repeated++;maps[r.station].set(r.ts,r.value)}
  for(const s of B.stations)S.records[s.id]=[...maps[s.id]].sort((a,b)=>a[0].localeCompare(b[0]));let persisted=true;if(changes.length)try{const db=await openDB();await new Promise((resolve,reject)=>{const tx=db.transaction('changes','readwrite');for(const r of changes)tx.objectStore('changes').put(r);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)});db.close()}catch{persisted=false}
  updateModels();render();status.textContent=`${added} leituras novas; ${revised} revisadas; ${repeated} já cadastradas. ${persisted?'Alterações salvas neste navegador.':'Persistência indisponível; exporte a série antes de fechar.'}`;$('footer-update').textContent='Última importação: '+new Date().toLocaleString('pt-BR');
 }catch(e){status.textContent=`Importação não concluída: ${e.message}`}}
function exportCSV(){const rows=['estacao;data_hora;regua_m;NR_m;altura_NR_m'];for(const s of B.stations)for(const [ts,v] of S.records[s.id])rows.push(`${s.name};${ts};${v};${s.nr};${A.round(v-s.nr)}`);const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff'+rows.join('\n')],{type:'text/csv;charset=utf-8'}));a.download='hidrometria-zp1-integrada.csv';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),2000)}
async function start(){await loadChanges();updateModels();choices();render();document.querySelectorAll('[data-view]').forEach(e=>e.addEventListener('click',()=>setView(e.dataset.view)));$('river').addEventListener('change',e=>{S.river=e.target.value;render()});$('station').addEventListener('change',e=>{S.station=e.target.value;render()});$('year-switches').addEventListener('click',e=>{const b=e.target.closest('[data-year]');if(!b)return;const y=Number(b.dataset.year);S.years.has(y)?S.years.delete(y):S.years.add(y);renderYears();drawChart()});for(const id of ['window','reference','forecast-short','band'])$(id).addEventListener('change',()=>{renderSummary();drawChart();if(S.view==='referencia')renderReference()});$('chart').addEventListener('pointermove',hover);$('chart').addEventListener('pointerleave',()=>$('tooltip').hidden=true);$('upload').addEventListener('change',e=>{if(e.target.files[0])importFile(e.target.files[0])});$('export').addEventListener('click',exportCSV);$('sounding').addEventListener('input',calcDepth);$('same-nr').addEventListener('change',calcDepth);if('ResizeObserver'in window)new ResizeObserver(()=>{if(S.view==='previsao')drawChart()}).observe($('chart').parentElement);if('serviceWorker'in navigator&&location.protocol==='https:')navigator.serviceWorker.register('sw.js').catch(()=>{})}
start().catch(e=>{$('error').hidden=false;$('error').textContent='Não foi possível iniciar o painel: '+e.message});
})();
